# Generated by Django 2.2.1 on 2019-06-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_plate_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='meals',
            field=models.ManyToManyField(related_name='plates', to='meals.Meal', verbose_name='Comidas'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
