# Generated by Django 2.2.1 on 2019-06-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meals', to='tags.Tag'),
        ),
    ]
