# Generated by Django 2.2.1 on 2019-06-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20190610_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meals', to='tags.Tag', verbose_name='Etiquetas'),
        ),
    ]
