version: "3"

services:
  db:
    container_name: "postgres"
    restart: always
    image: postgres:alpine
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_web:/var/lib/postgresql/data
  web:
    container_name: "nora_web"
    build: .
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8900"]
    volumes:
      - .:/code
    ports:
      - "8900:8900"
    depends_on:
      - db
    links:
      - db

volumes:
  database_web:
