# Generated by Django 2.2.1 on 2019-06-10 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distribution',
            name='slack_id',
            field=models.CharField(max_length=200),
        ),
    ]
