# Generated by Django 2.2.1 on 2019-06-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_auto_20190610_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='slack_id',
            new_name='link_id',
        ),
    ]
