# Generated by Django 2.2.1 on 2019-06-11 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0003_auto_20190610_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='distribution_hour_link',
            field=models.TimeField(default=datetime.datetime(2019, 6, 11, 5, 17, 59, 662312, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
