# Generated by Django 2.2.1 on 2019-06-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0005_auto_20190611_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='link_id',
            field=models.CharField(help_text='<code_id>/<code_id>/<code_id>', max_length=200, verbose_name='Link de envío'),
        ),
    ]
