# Generated by Django 2.2.1 on 2019-06-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0006_auto_20190613_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='link_id',
            field=models.CharField(help_text='Example: https://hooks.slack.com/services/*LINK*', max_length=200, verbose_name='Link de envío'),
        ),
    ]
