# Generated by Django 2.2.1 on 2019-06-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='plates',
            field=models.ManyToManyField(related_name='menus', to='plates.Plate', verbose_name='Platos'),
        ),
    ]
