# Generated by Django 2.2.1 on 2019-06-10 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ('menu_delivery_id',)},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='menu_delivery_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
