# Generated by Django 2.2.1 on 2019-06-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_plate_owner'),
        ('deliveries', '0002_auto_20190610_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_selection', to='deliveries.Delivery')),
                ('plates', models.ManyToManyField(related_name='delivery', to='plates.Plate')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
