# Generated by Django 2.2.1 on 2019-06-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_auto_20190612_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='distributions.Distribution'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='menus.Menu'),
        ),
    ]
