# Generated by Django 2.2.1 on 2019-06-13 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0005_auto_20190613_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryselection',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_selection', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
