# Generated by Django 2.2.1 on 2019-06-14 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_deliveryselection_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryselection',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_selection', to='deliveries.Delivery'),
        ),
    ]
