# Generated by Django 2.2.1 on 2019-06-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_auto_20190613_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryselection',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='deliveryselection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='deliveryselection',
            name='plates',
            field=models.ManyToManyField(related_name='delivery', to='plates.Plate', verbose_name='Platos'),
        ),
    ]
